### PR TITLE
Extended software list + alphabetical order

### PR DESCRIPTION
**Pull request by FxKu**
Hey there,
I've added HALE and ogc-schemas. CityEditor has already been added in the meantime :)
+ I've rearranged the list to alphabetical order. Hope that's ok.

### CODE REVIEW

**Comment by hugoledoux** [comment]
Cheers. Sorting wasn't necessary, or it's waaaaayyy simpler to sort in the code, Jekyll/Liquid has functions for this. I'll sort everything alphabetically so that no one accuses us of favouring some software.

**Comment by hugoledoux** [comment]
@FxKu in file `./software/index.md`the names of software are sorted

```
{% assign software = site.data.software | sort: 'name' %}
```

But that does it case-sensitive... I have been trying to circumvent this, but it's messy so now it's good enough. When Jekyll implement Liquid v4 there's a `sort_natural` function, so the problem will sort itself soon.

**Comment by kenohori** [comment]
I made a small plug-in for case-insensitive sorting in our group website, so I just copied it here. It works.

**Comment by hugoledoux** [comment]
brilliant, thanks

**Pull request merged**
